### ISSUE TITLE
无法使用手机号登录

### ISSUE THREAD

**Issue by maplewizard** [7sDream/zhihu-oauth#10]
提示输入验证码，但是输入后，显示
    
    验证码会话无效 :(

请问如何解决？
已经重试了很多次。

**Comment by 7sDream** [comment]
![](http://ww1.sinaimg.cn/large/88e401f0gw1f3f7c0av9vj20jt09dmzo.jpg)

尝试多次，均无法复现你所说的情况。

**Comment by 7sDream** [comment]
如果你已经解决了问题……请评论说明解决方法……

如果你还没解决，请评论说明如何复现这个问题方便开发者分析

别就提个问然后就咋样都不管了好咩……

**Comment by maplewizard** [comment]
抱歉，我的登录代码如下：
name = '134******74'
pwd = '********'
try:
    client.login(name, pwd)
except NeedCaptchaException:
    with open('a.gif', 'wb') as f:
        f.write(client.get_captcha())
    captcha = raw_input('please input captcha:')
    a = client.login(name, pwd, captcha)
    print a[1]
输出：

请输入正确的手机号

用正常网页可以登录

**Comment by 7sDream** [comment]
不是说好错误信息是验证码会话无效么……

唔，好吧先不管这么多，明早我起来去测试一下。

**Comment by maplewizard** [comment]
恩，下午测就变这样了

**Comment by maplewizard** [comment]
@7sDream 你好，今天测试依然是这个问题，不知道怎么解决？

**Comment by 7sDream** [comment]
@maplewizard 

由于我没有绑定手机号…也不想去绑定手机号……所以一直没法测试

如果可能的话还是用email试试。

**Comment by maplewizard** [comment]
@7sDream 我可以提供账号测试

**Comment by 7sDream** [comment]
@maplewizard 

加群：478786205

**Comment by maplewizard** [comment]
解决：手机账号需要添加  +86
