### ISSUE TITLE
获取话题内容下的问题没有详细说明啊

### ISSUE THREAD

**Issue by 0nise** [7sDream/zhihu-oauth#100]
获取话题内容下的问题没有详细说明啊，能否给说明一下，3Q

**Comment by 7sDream** [comment]
可以使用 [`Topic.activites`](http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/topic.html#zhihu_oauth.zhcls.topic.Topic.activities) 或者 [`Topic.unanswered_questions`](http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/topic.html#zhihu_oauth.zhcls.topic.Topic.unanswered_questions)。

请配合[阅读说明](http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/intro.html)一起食用。
