### ISSUE TITLE
在print特定模块的时候出现" <built-in method format of str object at 0x103..."的结果，如何将内容取出呀？

### ISSUE THREAD

**Issue by helixg** [7sDream/zhihu-oauth#102]
`topic_num = 265770568
question = client.question(topic_num)

ans = []
for answer in question.answers:
    ans.append(question.detail.format)
ans`
我跑了几秒钟就终止了，但是出来的内容都是这样的：
`0    <built-in method format of str object at 0x103...
1    <built-in method format of str object at 0x103...
2    <built-in method format of str object at 0x103...
3    <built-in method format of str object at 0x103...
4    <built-in method format of str object at 0x103...
5    <built-in method format of str object at 0x103...
6    <built-in method format of str object at 0x103...
7    <built-in method format of str object at 0x103...
8    <built-in method format of str object at 0x103...
9    <built-in method format of str object at 0x103...
10   <built-in method format of str object at 0x103...
11   <built-in method format of str object at 0x103...
12   <built-in method format of str object at 0x103...
13   <built-in method format of str object at 0x103...
14   <built-in method format of str object at 0x103...
15   <built-in method format of str object at 0x103...
16   <built-in method format of str object at 0x103...
17   <built-in method format of str object at 0x103...
18   <built-in method format of str object at 0x103...
19   <built-in method format of str object at 0x103...
20   <built-in method format of str object at 0x103...
21   <built-in method format of str object at 0x103...
22   <built-in method format of str object at 0x103...
23   <built-in method format of str object at 0x103...
24   <built-in method format of str object at 0x103...
25   <built-in method format of str object at 0x103...
26   <built-in method format of str object at 0x103...
27   <built-in method format of str object at 0x103...
28   <built-in method format of str object at 0x103...
29   <built-in method format of str object at 0x103...
..                                                 ...`
我找了半天都没找到该如何取出"question.detail.format"里面的内容，不过我按照官方文档中对于
"Answer.suggest_edit "的print就没有问题，可以把Streaming JSON打印出来，求老哥解惑呀~~~

**Comment by 7sDream** [comment]
`Question.detail` 是普通属性啊，他就是个 `str` 类型的数据，你直接 `print` 出来就行了。

`str.format` 是 Python `str` 对象的自带方法来着……你为啥要 `append` 一个方法……

**Comment by helixg** [comment]
每一个问题中的每一个答案好像都有一个ID，想取出question下每一个的answer的content该用哪一个呢？是需要先取出question下的每一个answer的ID然后再遍历吗？

**Comment by 7sDream** [comment]
直接在 for 循环里用 answer.content 就好了呀

**Comment by helixg** [comment]
感谢老铁这么晚还回复(◍•ᴗ•◍)❤我白天试试

**Comment by helixg** [comment]
在遍历评论者name的时候出现了type error，单独取出则没问题
for ans.author.name
出现了
TypeError: 'Answer' object is not iterable
直接print
print(ans.author.name)则OK，这是啥原因呢

**Comment by 7sDream** [comment]
他是个字符串，你为什么要用 `for` 呢

**Comment by 7sDream** [comment]
无后续讨论，暂时关闭。
