### ISSUE TITLE
如何拿到conversation(查看对话)的数据啊？

### ISSUE THREAD

**Issue by zylm** [7sDream/zhihu-oauth#104]

**Comment by 7sDream** [comment]
http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/comment.html#zhihu_oauth.zhcls.comment.Comment.conversation

**Comment by helixg** [comment]
为啥拿到的评论文本都是一个字一行的……

**Comment by 7sDream** [comment]
@helixg 能大概给个代码例子吗，我好复现查查问题。
