### ISSUE TITLE
关于Fiddler https抓包

### ISSUE THREAD

**Issue by jomonylw** [7sDream/zhihu-oauth#105]
请问是否现在Fiddler还能成功抓包呢?我使用Fiddler 进行抓包，并按照您在文档中的配置进行设置，且安装了证书，在Android端设置代理连接电脑端，并成功抓包了如豆瓣等App的https请求，但是知乎却还是无法抓取，app报无法获取数据 。恳请指教现在是用什么方法进行抓包的？谢谢！

**Comment by 7sDream** [comment]
嗯，你是用的 7.0 以上系统吗？可能是因为 7.0 新增加的一个安全策略导致的。
具体链接我以后给你贴一下，你可以尝试用模拟器（genymotion 等）+6.0的系统+Fiddler 尝试下。

**Comment by jomonylw** [comment]
@7sDream是的，我用的是7.0以上的系统。我先试试您说的这种方法，链接您有空贴出来分享一下，谢谢！

**Comment by 7sDream** [comment]
https://developer.android.com/training/articles/security-config.html

官方对于 7.0 的这个特性的说明文档见上，6.0 的话我当时尝试是没有问题的。

**Comment by jomonylw** [comment]
@7sDream十分感谢！！！
