### ISSUE TITLE
获取topic下best_answerers失败

### ISSUE THREAD

**Issue by airqj** [7sDream/zhihu-oauth#11]
![screenshot-21](https://cloud.githubusercontent.com/assets/2778047/15008591/ef5adcbc-1213-11e6-8da2-126c719f5b20.png)

这个是错误的截图

```
topic = client.topic(19942170)
for people in topic.best_answerers:
    print(people.name)
```
这个是相关代码，不知道各位有碰到这问题吗

**Comment by 7sDream** [comment]
待我实验一下。

**Comment by 7sDream** [comment]
已确认是bug，会在下一版本修复。

**Comment by 7sDream** [comment]
已更新。

请更新到 0.0.8 版本，再提供一下反馈吧，如果没问题了请关闭 Issue 谢谢~~

**Comment by airqj** [comment]
确认已修复
:+1:
