### ISSUE TITLE
求助（限流）（下载限制）

### ISSUE THREAD

**Issue by dearCorazon** [7sDream/zhihu-oauth#110]
我想要把知乎某个问题下的所有回答（现在有6000多个答案）全部下载下来再处理，然而只下载下来2000 多个回答就被封了，请问有没有什么好的办法呢？
我之前想的是每次下载两千个回答，再换账号，然而answer.save 方法下没有提供比如下载从第1个到第2000个回答

**Comment by 7sDream** [comment]
```python
for answer in question.answers.jump(2000):
    answer.save()
```

试下，不保证一定有效。

**Comment by 7sDream** [comment]
@dearCorazon  如果 OK 了请关闭 Issue 哈。
