### ISSUE TITLE
如何获取网络返回的原始json数据呀？

### ISSUE THREAD

**Issue by DNACore** [7sDream/zhihu-oauth#111]
我刚刚学python不久，可能有的地方也不是很清楚。以下有两个问题：

1. 

我想问问如何获取 question answer comment 原始的返回数据啊？
我看代码里 Base 类的pure_data方法可以获取，通过 `pure_data['data']`可以拿到原始的json返回数据。
在question类这个方法返回的数据是正常的，但是answer类还有comment类里面 pure_data['data']取出来就是个null了。

求教该如何获取啊？

2. 

还有一个其他问题，知乎应该是限制了api调用频率的，这个库有默认做出限制或者有什么函数可以设置api调用频率吗？

**Comment by 7sDream** [comment]
因为如果你不获取某个对象的某个非缓存里存在的属性的话，默认是会使用缓存中的数据。

比如：你从一个 answer 里获取答主信息 `answer.author`，因为答主的信息在 `answer` 对象里默认会有一部分，比如说昵称等等，这时候为了性能考虑并不会访问网络，所以他是个 null。

如果你非要得到网络上的最新数据，可以先调用一下 `something.refresh()` 方法。

---

这个没有，请自行实现。

**Comment by 7sDream** [comment]
三天未回复，暂时关闭。
