### ISSUE TITLE
关于登录状态与答案的一些疑问

### ISSUE THREAD

**Issue by ASC8384** [7sDream/zhihu-oauth#112]
您好，首先对您的贡献表示衷心的感谢。
1. 有些数据不用登录也可以获取，譬如答案，这样就可以减小帐号被ban 的机率。
但http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/client.html#zhihu_oauth.client.ZhihuClient.answer 显示Client 一点要是登录状态，不知这是为何？
2. 如果想获取已折叠答案，又该如何做呢？
3. 因为想保存当前状态，故答案获取时能否按时间排序？

**Comment by 7sDream** [comment]
1. 因为这个库的初衷只是做一个 Client API 的封装，用的是知乎 Android 端的 OAuth API，并不是网页。你可以尝试在浏览器的 **隐私模式** 中访问 `https://api.zhihu.com/answers/363457078` 这个地址试下，这就是代码里会使用的获取答案数据的 API，不登录的情况下是会报错的。另外，这个项目也没有考虑过任何为爬虫服务的情况，这 **不是** 也 **不适合** 当一个爬虫的基础库，所以也不考虑速度过快导致被 Ban 的情况。你把它当做一个正常的 Client API，做一个第三方知乎客户端啥的，是没有被 Ban 这种问题的。
2. 知乎应该是有接口的，但是我印象里好像我没封装……
3. 同 2，但是我依稀记得用户的回答列表是支持按赞数或者时间排序，问题的回答列表不太记得了，我需要确认下。

**Comment by 7sDream** [comment]
第三条这个，你可以尝试使用 `for answer in question.answers.order_by('created')` 这种写法试试，说不定可以。

**Comment by ASC8384** [comment]
好吧，~~~请问有开发爬虫的打算吗😂~~~。
第三点它默认是按默认来的。不过用`for answer in question.answers.order_by('created')`的话，是按时间顺序的，但这样如果有新回答就尴尬了，请问如何逆序？

**Comment by 7sDream** [comment]
没有。

用 `created` 的话，你可以记录一个之前访问过答案列表里创建时间最晚的答案。然后下次还是从第一个开始，发现答案比之前的那个记录时间还早就停下就行了呀。

**Comment by ASC8384** [comment]
啊，对，突然魔障了。
谢谢您的指点。

**Comment by ReactiveCJ** [comment]
好像也不是全部接口都需要登录态，比如https://api.zhihu.com/questions/304927212 就不需要登录
