### ISSUE TITLE
Generator 获取数据时出现 UnexceptedResponseException

### ISSUE THREAD

**Issue by airqj** [7sDream/zhihu-oauth#12]
![screenshot-19](https://cloud.githubusercontent.com/assets/2778047/15147102/7602090c-16f1-11e6-9136-fd96d887b6f5.png)

如截图所示
是不是知乎的反爬虫策略返回了无效数据？

**Comment by 7sDream** [comment]
可能是爬的太快……
用try catch包一下吧先，我下个版本试着在内部弄一下自动重试……
