### ISSUE TITLE
抓下来的answer的comment·如何保存下来

### ISSUE THREAD

**Issue by kamiyohaluowen** [7sDream/zhihu-oauth#125]
利用之前作者给我码，我成功抓取了comment，现在在为如何保存着急，请大神指教。
还有for comment in answer.comments:
    print(comment.content)
这个码是要把comment显示出来我是知道的，后面除了content以外有哪些键值，键叫什么名字（就是comment.后面的什么什么）以及对应的值是什么也想请教具体的，比如（每个回复的时间，有没有对应的要素（键值对）能查询）

**Comment by 7sDream** [comment]
文档里都有……
http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/comment.html

**Comment by kamiyohaluowen** [comment]
没有save吗？我想把抓下来的comment都保存下里，最好是txt文档

**Comment by 7sDream** [comment]
那你自己 open file 然后写进去就好了……

**Comment by kamiyohaluowen** [comment]
啊，大神我没有别的意思，身为编码的我只是想充分利用您的作品，如果惹您不快实在是抱歉，

**Comment by 7sDream** [comment]
额，没啥没啥……

不过我建议用第三方 Module 之前尽量把 Python 基础都了解下比较好~
