### ISSUE TITLE
登录出错

### ISSUE THREAD

**Issue by GuangyuanWang** [7sDream/zhihu-oauth#13]
使用建议登录方式：client.login_in_terminal(user,password)并输入captcha之后
返回：“Login failed, reason:  UnexpectedResponse”

**Comment by 7sDream** [comment]
Bug 已确认。

原因是知乎返回的 Token Json 和其他帐号登录时的返回不一样，缺少了两个未知字段，于是现有代码判断此 Token 无效。（真是奇怪的 Bug…………

将在下次更新时修复。

**Comment by 7sDream** [comment]
0.0.10 已修复。

**Comment by GuangyuanWang** [comment]
赞
