### ISSUE TITLE
OAuth 的登录不是应该跳转到知乎操作吗？

### ISSUE THREAD

**Issue by liwanglin12** [7sDream/zhihu-oauth#14]
还有Appkey和Appsecret(っ*´Д`)っ

**Comment by 7sDream** [comment]
但是现在知乎的 OAuth 接口并没有开放呀……

目前现在用的是我反编译出来的 Android APP 的 Key 和 Secret，用的是纯 Password 的验证方式。

如果你知道哪里能申请到知乎的 OAuth APPKEY 请告诉我 QAQ……

**Comment by liwanglin12** [comment]
。。。有点好奇你这样怎么获取accesstoken之类的东西？
---- 原始邮件 ----
发件人:"七秒不觉梦"<notifications@github.com>;
发送时间:2016年5月21日(星期六) 下午4:47
收件人:"7sDream/zhihu-oauth"<zhihu-oauth@noreply.github.com>;
抄送人:"liwanglin12"<i@lwl12.com>;"Author"<author@noreply.github.com>;
主题:Re: [7sDream/zhihu-oauth] Oauth的登录不是应该跳转到知乎操作嘛。。 (#14)


但是现在知乎的 OAuth 接口并没有开放呀……
 
目前现在用的是我反编译出来的 Android APP 的 Key 和 Secret，用的是纯 Password 的验证方式。
 
如果你知道哪里能申请到知乎的 OAuth APPKEY 请告诉我 QAQ……
 
&mdash;

**Comment by 7sDream** [comment]
过程在：http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-dev/oauth/game.html
