### ISSUE TITLE
关于topic中没有数据的问题

### ISSUE THREAD

**Issue by zhizunlo** [7sDream/zhihu-oauth#142]
![image](https://user-images.githubusercontent.com/34407842/51183043-1211c580-190b-11e9-82e4-5c22dca7eb49.png)
现在我关注的几个话题都是返回没有资源错误

**Comment by lpa123456** [comment]
![image](https://user-images.githubusercontent.com/34407842/51184185-7bdf9e80-190e-11e9-8ca5-b1a5e0e81f74.png)
就是在topic获取索引的时候就是这样

**Comment by lpa123456** [comment]
在获取best_answer时没有数据
