### ISSUE TITLE
为啥我没有找到回复私信的方法呢？

### ISSUE THREAD

**Issue by KLordy** [7sDream/zhihu-oauth#146]
是我眼拙脑子笨还是确实就压根没有呢。。。

**Comment by 7sDream** [comment]
https://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/me.html#zhihu_oauth.zhcls.me.Me.message

直接这个就行。

虽然我已经不用知乎很久了，这个库也不确定还能不能用了。

**Comment by KLordy** [comment]
哈哈哈  果然是我眼拙脑子笨，居然没发现，大部分功能还是可以用的，私信试了也是成功了！十分感谢~

**Comment by 7sDream** [comment]
😄
