### ISSUE TITLE
SSLError, 登陆失败

### ISSUE THREAD

**Issue by iiidi** [7sDream/zhihu-oauth#15]
![ssl_error](https://cloud.githubusercontent.com/assets/19668481/15676531/22e76e2c-2779-11e6-894b-fe6a4c03524a.jpg)

**Comment by 7sDream** [comment]
我这里测试了几次都没出现这个问题……

请问现在登录还有这个问题么？

顺便请提供一下你用的 Python 版本和 zhihu_oauth 版本。

**Comment by iiidi** [comment]
还存在这个问题，python 版本是2.7.11，zhihu_oauth 版本是0.0.12，用 python3 也是这个情况，输出信息稍稍有点不同，但也是抛出 SSLError ，不能登录，不知道其他人有没有这个情况 :sob:

**Comment by knarfeh** [comment]
今天也出现了这个问题，这个是解决方案：http://stackoverflow.com/questions/10667960/python-requests-throwing-up-sslerror

**Comment by iiidi** [comment]
@knarfeh 感谢，已经解决。
