### ISSUE TITLE
可以给发表评论或者给答案点赞吗？

### ISSUE THREAD

**Issue by duhaitao2016** [7sDream/zhihu-oauth#150]
你好，可以给发表评论或者给答案点赞吗？
我看[urls](https://github.com/7sDream/zhihu-oauth/blob/master/zhihu_oauth/zhcls/urls.py)这里有相关的接口：

- ANSWER_VOTERS_URL = ANSWER_DETAIL_URL + '/voters'
- SEND_COMMENT_URL = ZHIHU_API_ROOT + '/comments'

请问有对应的方法可以调用吗？

如果同时登陆多个用户 会有问题吗，是不是要开代理？

**Comment by 7sDream** [comment]
发表评论：https://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/me.html#zhihu_oauth.zhcls.me.Me.comment
点赞：https://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/me.html#zhihu_oauth.zhcls.me.Me.vote

这个库我自己已经很久没用过了，不太确定这些功能是否还有效。

可以试试。

**Comment by duhaitao2016** [comment]
非常感谢你的回复
