### ISSUE TITLE
从今天下午开始出现 HTTP 连接错误

### ISSUE THREAD

**Issue by ProtossProbe** [7sDream/zhihu-oauth#16]
本来设置了一个每隔半小时都跑一遍的 python 脚本用于扒取数据，之前一直用的好好的，今天下午开始出现：
`requests.exceptions.RetryError: HTTPSConnectionPool(host='api.zhihu.com', port=443): Max retries exceeded with url: /captcha (Caused by ResponseError('too many 500 error responses',))`
请问是api的原因还是我自己网络连接的原因呢？？

**Comment by yushroom** [comment]
我也出现这样的问题

**Comment by knarfeh** [comment]
同出现这个情况，知乎应该是有防爬虫的措施了

**Comment by YongLing** [comment]
同样的问题。。。是不是知乎改接口了？

**Comment by dss886** [comment]
同问题，一开始以为是被封IP了，换了IP还是不行，
然后以为是封账号了，换了帐号也不行。。。

**Comment by 7sDream** [comment]
这么多人都有同样的问题那我今天去看看好吧 对不住因为最近是考试周……我尽快修复。

**Comment by 7sDream** [comment]
@ProtossProbe @yushroom @YongLing @dss886 

我更新了 0.0.14 版本，我这里测试问题已经解决，你们更新了试试吧。

有时间的话尽量回来反馈一下，谢谢。

**Comment by 7sDream** [comment]
啊，对了，如果你们是用 load token file 方式登录的话，最好重新生成一次 token file。

**Comment by ProtossProbe** [comment]
@7sDream 问题已经修复，非常感谢！
