### ISSUE TITLE
获取article.column 报错

### ISSUE THREAD

**Issue by jomonylw** [7sDream/zhihu-oauth#18]
people = client.people('14c43fd66aa5f18ca9b20c7e384a176a')

print '----articles-----'
for article in people.articles:
    print article.id,article.title,'>>>',article.column.title

output:
`----articles-----
21552854 我的第二本电子书 >>> 迷宫中的银行
21532304 Sgt Pepper 的 Live －－ 商业银行不良资产大起底 >>> 迷宫中的银行
21484227 一个没什么人关注的货币指标 >>> 迷宫中的银行
21366123 我们可能都忽略了的投资产品 >>> 迷宫中的银行
20914821 商业银行年报分析 —— 首次 Live 后记 >>> 迷宫中的银行
20906883 Sgt Pepper 的 Live —— 商业银行年报分析 >>>
Traceback (most recent call last):
  File "/Users/huangzumou/Documents/PycharmProjects/zhihu-oauth-master/test2.py", line 31, in <module>
    print article.id,article.title,'>>>',article.column.title
  File "/Users/huangzumou/Documents/PycharmProjects/zhihu-oauth-master/zhihu_oauth/zhcls/other.py", line 57, in wrapper
    return cls(cache['id'], cache, self._session)
TypeError: 'NoneType' object has no attribute '__getitem__'`

是什么原因呢？

**Comment by 7sDream** [comment]
@jomonylw 

已确认是个 Bug，初步分析应该是和知乎新推出的 Live 有关，我尽快修复。

**Comment by 7sDream** [comment]
@jomonylw 

问题已查明。是因为知乎 Live 的相关文章都放在一个专门的专栏 [知乎 Live](https://zhuanlan.zhihu.com/zhihulive) 中，而在 API 获取文章的资料时，返回的数据里没有「所属专栏」这一项，所以获取的时候会出错。

以下为 APP 内截图：

![正常文章截图，界面显示所属专栏](http://ww2.sinaimg.cn/large/88e401f0jw1f620cjk2hzj20xc0hgn0o.jpg)

可以看到红色部分标出了所属专栏。

而那篇 Live 文章则没有，见下图：

![Live 文章截图，界面没有显示所属专栏](http://ww2.sinaimg.cn/large/88e401f0jw1f620dbc30fj20xc0fkac3.jpg)

所以这也是知乎 API 上的一个 Bug 吧，或者知乎本来就把这个 Live 专栏做了特殊处理。

以上是错误发生的原因，解决方案正在编写中。

**Comment by 7sDream** [comment]
@jomonylw 

0.0.15 版本修复了这个问题，但是因为有些文章没有专栏，所以使用 article.column 的时候需要先验证一下，比如这样：

```python
people = client.people('14c43fd66aa5f18ca9b20c7e384a176a')

for article in people.articles:
    print(article.id, article.title, end=' ')
    # 检查文章是否有所属专栏
    if article.column is not None:
        print(article.column.title)
    else:
        print("不属于任何专栏。")
```

以下是运行时截图：

![](http://ww1.sinaimg.cn/large/88e401f0jw1f620wt9dggj20hg0avdkj.jpg)

如果问题已解决请评论和关闭 Issue，谢谢~~~

**Comment by jomonylw** [comment]
谢谢！
