### ISSUE TITLE
People类的is_baned和is_locked似没有作用，该如何检测被封禁用户？

### ISSUE THREAD

**Issue by Link-KS** [7sDream/zhihu-oauth#19]
我原本以为被封禁的用户应该可以用这两个之一来检测出来，看来我想多了……
比如这个回答的答主：https://www.zhihu.com/question/28422616/answer/40838831
点击他的名字，会显示：该用户暂时被反作弊限制。
请问应该怎么检测这种情况呢？如果索取该用户的信息就会返回RetryError，用try...except...不能单独捕获这种情况

**Comment by 7sDream** [comment]
已经有个人发知乎私信给我提过这个 Bug 了……

原因已经查明，这个功能是近期知乎升级了悟空系统之后新加的，因为我对 400 错误设置了自动 10 次重试，而错误信息实际上是和 400 错误一起发回来的……所以它尝试 10 次之后会直接 raise exception 后面没法捕获到错误……

但是 400 错误的重试机制又不方便轻易取消……我正在想怎么处理这个问题。

目前你可以通过

```python3
from requests.adapters import RetryError
```

来导入这个 exception class，然后 except 它。

我会在下一个版本解决这个问题，到时候再来看怎么更优雅的处理好了……

**Comment by 7sDream** [comment]
@Link-KS 

0.0.16 版本已更新，现在的处理方法是这样（现在归类到 GetDataErrorExcetpion 里了）：

```python
from zhihu_oauth import ZhihuClient, GetDataErrorException

people = client.people('f7b18019729eea0f7183003a98384f17')

try:
    print(people.name)
except GetDataErrorException as e:
    print(e.reason)
```

结果：

```text
/usr/bin/python3.5 /home/i7sdream/code/zhihu-oauth/test/zhihu-mytest.py
该用户暂时被反作弊限制。

Process finished with exit code 0
```

如果有什么更好地建议请回复。
