### ISSUE TITLE
python2.7.9 无法登陆的问题

### ISSUE THREAD

**Issue by dancemoment** [7sDream/zhihu-oauth#20]
hey 7sDreams,
首先谢谢你的项目。
在使用你的zhihu_oauth时遇到的问题如下： 
环境：python 2.7.9

1)使用login登录
client.login('all***@***.com','*******')
提示：TypeError: data must be a byte string

2)使用login_in_terminal登录
client.login_in_terminal()
email:'****@****'
提示：TypeError: must be char, not unicode

是版本不同造成的问题还是说别的问题？ thanks for your time ^^

**Comment by 7sDream** [comment]
我去测试一下。

**Comment by 7sDream** [comment]
Linux 环境，我特意编译了一个 2.7.9 来测试，并没有不成功啊。见下图：

![](http://ww3.sinaimg.cn/large/88e401f0jw1f7ask8xh3oj20fs05wwg0.jpg)

请问你是 Windows 或者 Mac 环境么？

**Comment by dancemoment** [comment]
对的 在 win32环境下的
 - -

**Comment by 7sDream** [comment]
@dancemoment 

请给一下具体的 Windows 版本，32bit/64bit，方便我测试，蟹蟹~

**Comment by dancemoment** [comment]
<img width="644" alt="screen shot 2016-08-29 at 6 37 45 pm" src="https://cloud.githubusercontent.com/assets/13443770/18048950/cb89372e-6e17-11e6-8965-6399a6b260a5.png">
谢谢 @7sDream

**Comment by 7sDream** [comment]
问题差不多已查明……是 Python 自己的 Bug，目前看来和 [#1436203](http://bugs.python.org/issue1436203) 和 [1233785](http://bugs.python.org/issue1233785) 和 [#1578](http://bugs.python.org/issue1578)有关，我查看了 Python 的版本树，这个问题在 Python 3.0 rc0 就修复了，但是在 Python 2 版本中一直到 Python 2.7.11 都一直没有跟进……

Bug 已确认，下个版本我会修复的。

如果急着用的话，建议你先下个 Python 3。

**Comment by dancemoment** [comment]
好的，蟹蟹 @7sDream 如此耐心的解答
again, thanks for your time

**Comment by 7sDream** [comment]
@dancemoment 

0.0.16 版本已发布，尝试修复了一下这个问题，你更新一下试试，有什么问题请继续回复。

**Comment by dancemoment** [comment]
hey @7sDream,
蟹蟹。。。
将版本更新至0.0.16后，解决了输入email的问题，但在输入密码后，出现了与之前一样的问题，猜想应该是部分代码没有修改完全 （client.login() 以及client.login_in_teminal()），如图：
<img width="132" alt="screen shot 2016-08-29 at 11 00 34 pm" src="https://cloud.githubusercontent.com/assets/13443770/18056043/e6ad5a56-6e3c-11e6-92ea-429a8416556c.png">
此外，在ide运行时，输入完email后，无法运行出 输入password的代码行，供你参考：
<img width="518" alt="screen shot 2016-08-29 at 11 01 04 pm" src="https://cloud.githubusercontent.com/assets/13443770/18056117/30cbfc64-6e3d-11e6-9106-e091abc7af1a.png">

take your time,have a good night ^^

**Comment by 7sDream** [comment]
第一个问题比较奇怪，看 traceback 可以发现并不是输入密码的问题，而是发送登录请求的时候 requests 模块内部出了点问题，建议你更新一下 requests 的版本再试试，如果不行我再研究。

然后第二个问题我也已经发现了，我在用 PyCharm 测试的时候发现了这个问题。因为一般 IDE 的 console 都会对输入做一些处理，比如说拦截快捷键之类的，所以造成了底层的 `getpass.win_gerpass` 模块调用的 `msvcrt.getch` 函数阻塞了，所以会一直卡在这。（相关 REF：[](http://stackoverflow.com/questions/25263853/nothing-happening-with-msvcrt-getch-when-running-script-in-pycharm-3-4-x-conso)）

目前来看没有什么好办法，因为在 Linux 上不成文的规定是输入密码应该不回显在终端里，所以按习惯使用了 getpass 模块……而这个问题准确来说应该是 IDE 的 Bug，如果有可能我试着向 JetBrain 反应一下。

暂时的思路是在下次的更新中为 login_in_terminal 加一个参数用于控制是否使用 getpass 模块。

**Comment by 7sDream** [comment]
补一张 linux 2.7.9 下，最新版 zhihu_oauth 最新版 requests 的运行情况：

![](http://ww2.sinaimg.cn/large/88e401f0jw1f7b1rzd8t0j20fs05wwg0.jpg)

**Comment by 7sDream** [comment]
这个 Issue 只讨论你上面说的第一个问题，关于 IDE 里无法输入密码的问题到 #21 里讨论吧。

**Comment by dancemoment** [comment]
恩，requests是最新的版本 2.11.1，依然出现第一个问题
慢慢来

**Comment by 7sDream** [comment]
@dancemoment 

查找了一下，根据 Reddit 网友的说明，这**可能**是 Python 2.7.9 的 httplib 的一个 Bug。

相关 [REF]。(https://www.reddit.com/r/redditdev/comments/3uapp8/praw_error_data_must_be_a_byte_string/)。

但是根据 requests 的一个 Issue 的讨论，这也可能是 Python 的 ssl 模块的一个 bug。不过根据讨论，请求的 Header 最好不要使用 unicode，所以我也会把这里改一下。

相关 [REF](https://github.com/kennethreitz/requests/issues/2113)

因为我这里就算用 2.7.9 的版本也没复现你的问题，所以你可以先试试把 Python 升级到 2.7.10 或者更高版本，试试会不会好。

同时在下个版本我会尽量把不需要用到 unicode 的 header 改成 ascii。

**Comment by 7sDream** [comment]
我今天又装了 2.7.9 的 32bit 版本来测试，依旧无法复现这个 Bug 真是奇怪了：

![](http://ww4.sinaimg.cn/large/88e401f0jw1f7bjh5oov8j211y0jadmc.jpg)

稍后我会发一个 0.0.17 的版本，把 header 改成 ascii 模式。

（上图中的 use_getpass 参数可以解决无法在 IDE 中输入密码的问题）

**Comment by 7sDream** [comment]
0.0.17 已更新。

做了一点微小的工作，但因为我这里没法复现 Bug，所以不知道到底有没有解决……

（无法复现的 Bug 解决起来好麻烦……

**Comment by dancemoment** [comment]
@7sDream
2.7.9可以成功在python环境下登陆了，（IDE还存在一丢丢问题）。蟹蟹执着修复bug的 七秒不觉梦童鞋

**Comment by 7sDream** [comment]
@dancemoment 

那去那边 Issue #21 讨论吧，我把那边重新开，这个就关了~
