### ISSUE TITLE
无法在 PyCharm 等 IDE 内部的终端中登录？

### ISSUE THREAD

**Issue by 7sDream** [7sDream/zhihu-oauth#21]
今天发现的问题之一，原因是因为一般 IDE 的 console 都会对输入做一些处理，比如说拦截快捷键之类的，所以造成了底层的 `getpass.win_getpass` 模块调用的 `msvcrt.putch` 和/或 `msvcrt.getch` 函数阻塞/失败了，所以会一直卡在这。相关 [REF](http://stackoverflow.com/questions/25263853/nothing-happening-with-msvcrt-getch-when-running-script-in-pycharm-3-4-x-conso) 。

目前这个 Bug 的解决方式设想是：为 login_in_terminal 加一个默认为真的参数用于控制是否使用 getpass 模块。

可在此 Issue 下讨论更好的方式。

**Comment by dancemoment** [comment]
@7sDream  我来反馈情况咯
无法在IDE终端登陆的问题在zhihu_oauth 0.0.17中基本解决：
（1）client.login_in_terminal('***@***','****') 可以登录
（2）client.login_in_terminal(use_getpass = False) 键入email 后会显示要求输入password，可以登录
（3）client.login_in_terminal()   键入email后，堵塞了，无法显示输入password, 无法正常登陆
怎么感觉你在修bug中找乐趣呢，哈哈
again, thanks for your responses and time

**Comment by 7sDream** [comment]
@dancemoment 

额，这是正常的情况，因为新加的 use_getpass 就是用来解决 IDE 里无法输入密码的问题的，在 IDE 里登录的话就需要这个参数。

参见[更新说明](https://github.com/7sDream/zhihu-oauth/blob/master/changelog.md#0017)。

=，= 因为有 Bug 没修会有负罪感……
