### ISSUE TITLE
蛤？知乎503还是？

### ISSUE THREAD

**Issue by cxgreat2014** [7sDream/zhihu-oauth#22]
![image](https://cloud.githubusercontent.com/assets/15062548/18302272/80ea3922-7509-11e6-9391-09b140a8e152.png)

**Comment by maicWorkGithub** [comment]
关了吧，这是知乎服务器挂了，跟程序没关系。百度 503 Service Unavailable

**Comment by 7sDream** [comment]
恩，看上去是知乎今天出问题了，手机客户端那边也在报 503。

**Comment by cxgreat2014** [comment]
貌似和这个有关：http://www.freebuf.com/news/113877.html
