### ISSUE TITLE
讨论一个引入的问题～

### ISSUE THREAD

**Issue by Allianzcortex** [7sDream/zhihu-oauth#24]
最近在看源代码，整体结构非常清晰，划分的也很合理，厉害厉害～

想讨论一下 client 里面的一个问题：

在 `client.py` 中有下面的一行代码：

` from .oauth.before_login_auth import BeforeLoginAuth`

但在 oauth 里的 __init__.py 里已经引入了 BeforeLoginAuth ，所以是否可以直接换为

` from .oauth import BeforeLoginAuth`

毕竟 `__init__.py` 除了能标志 module 外还可以 reduce redundant import :8ball: 

同时在 `oauth/token.py` 中有

`from ..exception import MyJSONDecodeError`

如果是从外部模块引入的话，我更喜欢的是这样：

`from zhihu_oauth.exception import MyJsonDecodeError`

但这就属于个人喜好问题了 :-D

**Comment by Allianzcortex** [comment]
Re：https://www.reddit.com/r/Python/comments/1bbbwk/whats_your_opinion_on_what_to_include_in_init_py/

**Comment by 7sDream** [comment]
恩，第一个的话是可以的，我下次更新换换，虽然也没啥影响辣。

第二个问题的话我个人是比较喜欢相对引入的……所以暂时就不改辣~

**Comment by Allianzcortex** [comment]
校招顺利哦～

**Comment by 7sDream** [comment]
OvO 
Thank u ~
