### ISSUE TITLE
使用过期令牌尝试登录失败后再次登录显示“登录过于频繁”

### ISSUE THREAD

**Issue by Link-KS** [7sDream/zhihu-oauth#25]
两个星期没用zhihu-oauth，今天尝试登录，提示“令牌已过期”。删除过期令牌后重新登录，则提示“登录过于频繁，请稍后重试，或者联系 antispam@zhihu.com”，手机客户端和PC也无法登录了（不过还可以通过微博账号来登录……）。我想问一下这种情况是过期的登录令牌导致的吗？我这样应该还不算是被封禁吧？

**Comment by 7sDream** [comment]
登录过期令牌并不会有啥惩罚应该。

应该不算封禁，可能是由于前几天知乎服务器出了点问题把 Token 全给删了要求重新登录……然后又出了点问题

我猜想等个几小时就好，或者你给 antispam 发个邮件说明一下就说今天用 Android 登录登不上，应该会给处理的。

**Comment by Link-KS** [comment]
刚刚尝试注册小号，结果提示“请求存在异常，请稍后再试”。猜测可能是封禁IP地址了……我现在就给antispam说一下吧

**Comment by Link-KS** [comment]
antispam没有回复。换了个新邮箱也换了台电脑，但还是无法注册。尝试让同学在手机4G环境下重新登录他自己的账号也遭遇了不能登录的情况。不知道是不是服务器出问题了。也有可能因为我人在香港，而知乎目前因为某些原因对香港的登录有所管制……

**Comment by Link-KS** [comment]
前几天知乎上线新版手机客户端后问题解决啦~
