### ISSUE TITLE
请问有获取话题日志的接口吗？

### ISSUE THREAD

**Issue by strrchr** [7sDream/zhihu-oauth#29]
http://zhihu-oauth.readthedocs.io/zh_CN/latest/index.html
看文档似乎是没有，不知道知乎有相应的api接口吗？
TOPIC_LOGS_URL = TOPIC_DETAIL_URL + '/log'
TOPIC_LOGS_URL = TOPIC_DETAIL_URL + '/logs'
试验了这两种，似乎都不行。

**Comment by 7sDream** [comment]
估计没有。因为用的是官方 APP 的 API，你去试试手机 APP 里找不着得到查看话题日志的地方……如果找不到那就是木有……可以反馈给知乎让他们加上 =。=

同理专栏文章的点赞者目前也没接口，sad。
