### ISSUE TITLE
请问有点收藏的接口吗？

### ISSUE THREAD

**Issue by maplewizard** [7sDream/zhihu-oauth#3]
是否有在登陆后收藏答案和关注某人的api？
===========
似乎在TODO list 里，希望作者能优先开发：）
Me 类的各种操作，比如评论，点赞，私信……etc

**Comment by 7sDream** [comment]
嘛，目前优先在写测试……一般TODO是按照顺序来的……所以可能要等一会……

（加上最近学校的项目中期检查，所以可能开发进度会慢一点，抱歉QAQ

**Comment by 7sDream** [comment]
如果我没理解错，你需要的应该是收藏答案吧？

如果是的话刚刚写完了，应该在下一版本 0.0.5 就会有这个功能了。发布 0.0.5 的时候我会 at 你的。

**Comment by 7sDream** [comment]
@maplewizard 

0.0.5 版本已发布，有收藏功能了。至于怎么用请看[文档](http://zhihu-oauth.readthedocs.org/zh_CN/latest/for-user/zhcls/me.html#zhihu_oauth.zhcls.me.Me.collect)。
