### ISSUE TITLE
ImportError: No module named packages.urllib3

### ISSUE THREAD

**Issue by gerui0307** [7sDream/zhihu-oauth#32]
``` python
# /zhihu_oauth/client.py +11
import requests.packages.urllib3 as urllib3
```

报错：`ImportError: No module named packages.urllib3`

这个 requests.packages 是被移除了么？我在python2.7.6 和 python 3.4.3 下均没有找到这个模块。 

requests 的版本是2.11.1

能不能添加个兼容，直接导 urllib3 。

**Comment by 7sDream** [comment]
今天太晚了…我明早起来看看。

**Comment by 7sDream** [comment]
@gerui0307 你别骗我呀……我专门去 requests 的 repo 里看了一下，明明这个 requests.packages.urillib3 还在呀……

参见：https://github.com/kennethreitz/requests/tree/master/requests/packages/urllib3

So 我这里没法复现你这个问题……

你自己先尝试分析一下为什么你那里没法 Import？注意测试文件不要叫 requests.py，当前文件夹里也不要有。我只能想到可能是这个问题。

其实 urllib3 我也没用到什么，就用来把 SSL Warning 给禁用了，我考虑下个版本把这几行去掉吧。

**Comment by 7sDream** [comment]
请求反馈，问题排查的怎么样了？

不管解决没解决都麻烦说一下呗～

**Comment by cxgreat2014** [comment]
233333，我复现了，啥BUG都来找我

**Comment by 7sDream** [comment]
在 #43 中复现。

**Comment by shuizuo** [comment]
![Uploading IMG_0252.PNG…]()
![Uploading IMG_0253.PNG…]()
我也碰到了这个bug，不知道是什么原因，按照路径也找到了这个包，但不知道为什么有问题

**Comment by 7sDream** [comment]
你提供一下 Python 版本和操作系统，我明天有时间的话看看...... 这是什么鬼情况

**Comment by shuizuo** [comment]
ubuntu 14.04.4LTS（GNU/Linux 3.13.0-86-generic x86_64）
Python  2.7.6

**Comment by 7sDream** [comment]
@shuizuo 

根据这个 Issue：https://github.com/box/box-python-sdk/issues/57

可能是你的 requests 版本过低，你升级到最新版看看……

卸载掉系统的 python-requests 包，然后用 pip 装最新的。

**Comment by shuizuo** [comment]
按照这个Issue里提供的方案解决了问题，确实是系统requests版本太低了（2.2.1），在virtualenv中安装了2.12.1的，成功运行起来了，谢谢
