### ISSUE TITLE
answer.updated_time 属性返回值不是日期时间字符串

### ISSUE THREAD

**Issue by Ritalmc** [7sDream/zhihu-oauth#33]
哈哈~大神你好！转到你这个知乎项目来了，的确比上一个用着方便~~
可是我在抓该用户回答的所有问题的时间时用了updated_time这个属性，为什么是一个不是时间格式的东东？具体如下：
author = client.from_url('https://www.zhihu.com/people/tian-yuan-dong')
for answer in author.answers:
    print('Id:', answer.id, 'Question ID: ', answer.question.id, 'Question content:', answer.question.title,
          'Voteup_count:', answer.voteup_count, 'thanks_count:', answer.thanks_count, 'Comments_count:',
          answer.comment_count, 'answer date:', answer.updated_time)

输出结果：
Id: 123392610 Question ID:  50916351 Question content: 如何评价基于游戏毁灭战士（Doom）的AI死亡竞赛大赛结果？ Voteup_count: 463 thanks_count: 57 Comments_count: 27 answer date: 1474927259
Id: 119125243 Question ID:  49846394 Question content: 如何看待郝景芳的《北京折叠》获得第 74 届世界科幻大会上颁发的雨果奖最佳中短篇小说奖？ Voteup_count: 352 thanks_count: 53 Comments_count: 62 answer date: 1472237020

想抓的是具体时间~~

另外想获得该用户关注的人的url地址。。。按逻辑用following.url说没有这个属性~

可能很小很白的问题。。。希望大神帮忙~~

**Comment by strrchr** [comment]
answer date: 1472237020
这个东西叫做 unixtime
https://en.wikipedia.org/wiki/Unix_time

**Comment by Ritalmc** [comment]
Oops~哈哈，好的！再次暴露编程小白的特性-> ->谢大神科普噗~~

**Comment by 7sDream** [comment]
@strrchr 谢谢帮助回答～

@Ritalmc 

你好第二个问题可以在这里找到答案：https://github.com/7sDream/zhihu-oauth/issues/4
