### ISSUE TITLE
能增加一下问题日志的爬取功能吗？

### ISSUE THREAD

**Issue by 42binwang** [7sDream/zhihu-oauth#39]
您好，我觉得问题日志的功能也挺关键的，可以从问题日志中查到问题的提出者和问题的时间。

**Comment by 7sDream** [comment]
是这样的 这个项目基于的是知乎的 Android 客户端的 API，所以只能实现 Android 客户端里有的功能。我不太清楚客户端里看不看得到问题日志，如果有办法看到的话请给一下操作流程，我周末可以试着加一下。如果客户端里没这功能我也没办法。

**Comment by 42binwang** [comment]
我使用的iOS版是问题日志是可以在手机客户端查看的，
操作流程为点开问题，右上角更多（三个点），下方弹出的菜单有问题日志选项。

安卓客户端应该有类似的流程，我等会儿跟同学借一下安卓手机看看怎么操作～

谢谢。

**Comment by 7sDream** [comment]
iOS 端有的话那应该就可以，我周末试试吧，最近在实习平常都没啥时间、

**Comment by 42binwang** [comment]
我室友回来了，我看了一下他的手机，安卓端没有。好像只有iOS那端有，那这个功能还能做吗？

**Comment by 7sDream** [comment]
看情况 iOS有的话一般情况下是可以的 因为接口应该是共用的。等我闲下来帮你看看吧 需要稍等几天。

**Comment by 42binwang** [comment]
感谢。

**Comment by 7sDream** [comment]
@42binwang 

请问一下你会使用 fiddler 或者 BrupSuite 之类的软件抓 HTTPS 的包么？
我手头上没有 iOS 的设备，所以我猜不出知乎日志的 API 地址……所以没法开发这个功能。
如果你会的话就把获取 Log 的 API 地址发我一下，我应该能很快写出来。

如果不会的话可以看看我的这篇文档：http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-dev/oauth/game.html

不过这篇文档是以 Android 端的 Packet Capture 为例的，你可能需要研究一下 fiddler 或者 BrupSuite 的使用方法。

如果你没法找到 log 的地址的话可能就要等 11 月 13 号我回学校借同学的手机研究之后，才能把这个功能写出来了。

**Comment by 42binwang** [comment]
我抓包的结果显示好像这个功能是直接返回了一个页面。
<img width="1101" alt="screen shot 2016-11-05 at 11 17 19 pm" src="https://cloud.githubusercontent.com/assets/15713193/20031183/64ab9534-a3ae-11e6-8dc4-6eb487ac1272.png">

**Comment by 7sDream** [comment]
不是让你抓网页版的呀……是让你抓手机的。
开个代理让手机的流量过你这个软件，开头的地址应该是 https://api.zhihu.com

**Comment by 42binwang** [comment]
抓的就是手机版的，iOS的这个功能应该是打开了log页面。

**Comment by 7sDream** [comment]
那就没办法了呀……如果要支持页面的话这个项目的架构就要改，有点麻烦。
你可以通过 question.url 然后构造 log url 自己写个解析日志的函数。

**Comment by 42binwang** [comment]
好
