### ISSUE TITLE
获取到的用户ID为什么是hash串？

### ISSUE THREAD

**Issue by CHT2014** [7sDream/zhihu-oauth#4]
比如我直接访问‘an-yi-16’用户，返回的属性 id 还是 ‘an-yi-16’；
```
>>user = client.people('an-yi-16')
>>print(user.id)
    an-yi-16
```
当我访问该用户关注的一个用户时返回的 id 是如下的一串字符，请问该字符是什么编码，为什么和上面返回的不一样呢？
```
>>user.followings[0].name
    'T44的弹药架'
>>user.followings[0].id
    '5c0f6f13961b2764593fe2accc10e13d'
```
上面的用户的 id 为 ‘blacklancer’。

**Comment by 7sDream** [comment]
是这样的，知乎的people API接受两种ID，一种是人类可读的，就是主页URL最后的那一串，还有一种是知乎内部的hashid。
因为我在类的内部做了缓存（为了性能考虑，减少网络请求），你用人类可读的ID创建对象，这时候取ID是不会访问网络的，会返回对象里暂存的你输入的ID。你随意访问他的一个属性，比如name，然后再输出一遍ID，就会是hashID了。因为一旦访问了知乎的API，它返回的都是那种内部hashid。
因为取关注者的接口也是访问了网络的，所以输出也会是hashid。
另外，知乎的Web端也是可以用hashid访问的。
也就是说，你访问 https://www.zhihu.com/people/5c0f6f13961b2764593fe2accc10e13d 知乎会帮你自动重定向到 https://www.zhihu.com/people/blacklancer
我现在用的是平板，可能说的不是很清除，看得不明白的话等我明天起床编辑一下QAQ。另外有能力的话其实可以自己读读代码～

**Comment by CHT2014** [comment]
谢谢，看到代码了
