### ISSUE TITLE
能否获取到动态 Activity 的时间戳

### ISSUE THREAD

**Issue by brucezz** [7sDream/zhihu-oauth#40]
hi 7sDream, 
不知道有没有获取动态时间戳的方法。我想定时去拉去用户的动态列表，通过时间戳来判断上次拉去到的位置，然后做备份之类的操作。

 :octocat:

**Comment by 7sDream** [comment]
感觉上应该可以，但是目前确实没写。
暂时等我周末加吧，最近在实习有点忙……

**Comment by brucezz** [comment]
Cool!~

**Comment by brucezz** [comment]
@7sDream  我提了一个 PR(#42 ) 来解决这个 issue

**Comment by 7sDream** [comment]
OK 感谢，我闲下来的时候 merge 一下，在下个版本 release 的时候加入。

**Comment by brucezz** [comment]
Nice library ~ 感谢 😄

**Comment by 7sDream** [comment]
0.0.22 版本已发布。

**Comment by brucezz** [comment]
cool~ 我把 issue 关掉吧
