### ISSUE TITLE
抓取多层关注的人时，出现多次连续重复抓取某些人的现象是什么原因？

### ISSUE THREAD

**Issue by Ritalmc** [7sDream/zhihu-oauth#41]
我尝试以一个seed（seed_id = 'tian-yuan-dong'）为起点，抓取他的一些基本信息，然后再抓取这个seed关注的人（第二层），然后再以这些人为起点分别抓取他们关注的人的信息（第三层）。
write_excel（）是我自己写的一个函数，就是把获取到的信息填入excel。代码如下：

seed_id = 'tian-yuan-dong'
TOKEN_FILE = 'token.pkl'
if os.path.isfile(TOKEN_FILE):
    client.load_token(TOKEN_FILE)
    print('load_token')
else:
    client.login_in_terminal()
    client.save_token(TOKEN_FILE)

print("log info:" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())) + "crawl" + seed_id + "start")
user = client.from_url('https://www.zhihu.com/people/' + seed_id)
print("log info:" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())) + "crawl" + user.name + "end")
write_excel(user, 'Sample.xlsx')  # 第一层

print('****************Followees*********************')
# 第二层
for following in user.followings:
     user = client.from_url('https://www.zhihu.com/people/' + following.id)
     write_excel(user, 'Sample.xlsx')

print('****************the third level*********************')
for following in user.followings:
    user = client.from_url('https://www.zhihu.com/people/' + following.id)
    for each_following in user.followings:
        write_excel(user, 'Sample.xlsx')
在抓取信息的时候一开始都是没有问题的，但是后来从某一个用户开始就会接连重复出现好几次，如下（填入excel的信息），从此之后抓取的用户都是类似这样子重复的：
陈明  9908fb53afaaeb97f248ac193c75837a  分布式系统老兵，微信工程师  168   13
陈明  9908fb53afaaeb97f248ac193c75837a  分布式系统老兵，微信工程师  168   13
陈明  9908fb53afaaeb97f248ac193c75837a  分布式系统老兵，微信工程师  168   13
陈明  9908fb53afaaeb97f248ac193c75837a  分布式系统老兵，微信工程师  168   13
野生杨叫兽 4546452329453afdcfd3e534325c1e51 Quant Developer，自由自在的单身狗。Quant Developer  8532  7
野生杨叫兽 4546452329453afdcfd3e534325c1e51  Quant Developer，自由自在的单身狗。Quant Developer 8532  7
野生杨叫兽 4546452329453afdcfd3e534325c1e51  Quant Developer，自由自在的单身狗。Quant Developer  8532 7

觉得按照之前获取的信息应该不会出现这样的问题~但是事实就是我尝试抓取了好几次，仍旧会出现同样的问题，恳请大神帮忙解释一下 ： ）

**Comment by 7sDream** [comment]
先把你代码整理一下呀……我的哥，这谁能看得懂。

你先看看怎么用 Markdown 发代码把。

**Comment by Ritalmc** [comment]
Oops~不好意思啦，大哥哥~~ 没有看到代码原来变成那样了。。。下面是上面提到的代码
`seed_id = 'tian-yuan-dong'
TOKEN_FILE = 'token.pkl'
if os.path.isfile(TOKEN_FILE):
    client.load_token(TOKEN_FILE)
    print('load_token')
else:
    client.login_in_terminal()
    client.save_token(TOKEN_FILE)

user = client.from_url('https://www.zhihu.com/people/' + seed_id)
print("log info:" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())) + "crawl" + user.name + "end")
write_excel(user, 'Sample.xlsx')  # 第一层

print('****************Followees*********************')
# 第二层
for following in user.followings:
     user = client.from_url('https://www.zhihu.com/people/' + following.id)
     write_excel(user, 'Sample.xlsx')

print('****************the third level*********************')
for following in user.followings:
    user = client.from_url('https://www.zhihu.com/people/' + following.id)
    for each_following in user.followings:
        write_excel(user, 'Sample.xlsx')
`
后面的那些excel里面的信息就是表示获取的用户的名称，ID，headline。。。之类的，这个格式应该不用整理就能看懂吧？

**Comment by Ritalmc** [comment]
Oops, sorry, 大哥，没有注意到发出去的代码变成那样了。。。下面是代码部分：

```
seed_id = 'tian-yuan-dong'
TOKEN_FILE = 'token.pkl'
if os.path.isfile(TOKEN_FILE):
    client.load_token(TOKEN_FILE)
    print('load_token')
else:
    client.login_in_terminal()
    client.save_token(TOKEN_FILE)


print("log info:" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())) + "crawl" + seed_id + "start")
user = client.from_url('https://www.zhihu.com/people/' + seed_id)
print("log info:" + time.strftime("%Y-%m-%d %H:%M:%S", time.localtime(time.time())) + "crawl" + user.name + "end")
write_excel(user, 'Sample.xlsx')  # 第一层

print('****************Followees*********************')
# 第二层
for following in user.followings:
     user = client.from_url('https://www.zhihu.com/people/' + following.id)
     write_excel(user, 'Sample.xlsx')

print('****************the third level*********************')
for following in user.followings:
    user = client.from_url('https://www.zhihu.com/people/' + following.id)
    for each_following in user.followings:
        write_excel(user, 'Sample.xlsx')

```
后面的是excel 中抓取的信息，分别表示获取的用户名，id, headline.....这个应该好理解吧？
正在学习python和使用github中，有啥不懂的请各位大哥大姐不要见怪~

**Comment by Ritalmc** [comment]
呀~我知道问题出现在哪里了。。一个编程的错误，不好意思麻烦大神了~~谢谢谢谢~~
