### ISSUE TITLE
TypeError('Only dict and list can be StreamingJSON.')

### ISSUE THREAD

**Issue by thekoc** [7sDream/zhihu-oauth#44]
TypeError: Only dict and list can be StreamingJSON.
在试图获取 answer.suggest_edit.status 的时候出现的错误

**Comment by 7sDream** [comment]
感谢反馈，我等会测试一下。

**Comment by 7sDream** [comment]
我刚测试没问题呀，我用的我[这个答案](https://www.zhihu.com/question/52515935/answer/130906099)

截图：
![](http://rikka-10066868.image.myqcloud.com/b7e817a9-cfec-40b6-b512-c2de43ef625b.png)

请提供一下你的测试代码，Thx。
