### ISSUE TITLE
最新版本无法进入收藏夹

### ISSUE THREAD

**Issue by prid** [7sDream/zhihu-oauth#47]
```
for answer in collection.answers:
    print('hello')
```
经过测试,输出根本没有hello,所以说程序根本没有进入for loop

**Comment by prid** [comment]
经过测试，0.0.23表现征程，而0.0.24（以及之后）则不行。问题出在BaseGenerator中的_fetch_more中的
`res = self._session.get(self._next_url, params=params)`
经过测试，res的返回值是：{'error': {'code': 4040, 'message': 'URL 不存在'}}

**Comment by prid** [comment]
将0.0.23版本的oauth/settings.py替换最新版本的同名文件之后就没有问题了,

**Comment by 7sDream** [comment]
那应该是知乎更新 API 之后收藏夹的接口变了吧，今天可能没时间，我明天看看。

请稍等~

**Comment by 7sDream** [comment]
@prid 

唔，下午有时间先简单看了下，是因为知乎后来支持往收藏夹里收藏文章了，估计是他们觉得接口还叫 `collections/xxx/answers` 不太好，就改成 `collections/xxx/contents` 了……对于客户端版本小于某一数值的请求以前的 `answers` 接口还能用，但是我上次更新升级 API 版本之后这个接口就不让访问了……

那我这个接口可能也要改……我加一个 contents 接口吧，文章和答案都返回……然后 answers 接口改成从这个新接口里取数据……然后只返回类型是 Answers 的，做个兼容……

可能要改的地方比较多，耐心等等吧……=。=

**Comment by 7sDream** [comment]
0.0.28 已发布，应该可以了。

建议重新看一下 Collection 的文档：http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/collection.html

非常感谢指出 Bug，Mua~

**Comment by prid** [comment]
神速!谢大神
