### ISSUE TITLE
发送私信功能失效

### ISSUE THREAD

**Issue by ayxuerui** [7sDream/zhihu-oauth#48]
目前调用的是:
ZHIHU_API_ROOT = 'https://api.zhihu.com'
SEND_MESSAGE_URL = ZHIHU_API_ROOT + '/messages'

data = {
            'receiver_id': who.id,
            'content': content,
        }
res = self._session.post(SEND_MESSAGE_URL, data=data)

在网页端尝试发送私信：
Request URL:https://www.zhihu.com/api/v4/messages
Request Method:POST
Status Code:200 OK

Request:
{
type:"common"
content:"你好"
receiver_hash:"ddc9457e59e9c886d900c83025e43f3e"
}

**Comment by 7sDream** [comment]
![](http://rikka-10066868.image.myqcloud.com/aa093609-ee1d-43c0-8c99-0fd7a406fb0a.png)

![](http://rikka-10066868.image.myqcloud.com/c026737f-4d1e-4b83-9932-f16ba377738f.png)

我试了一下，功能没失效，还能正常使用啊……

能不能详细说明一下你那里失效的表现？

**Comment by ayxuerui** [comment]
谢谢回复！发现是我这边账号的问题

（有了succ和reason的返回，容易debug多了）

再次感谢！
