### ISSUE TITLE
请问搜藏夹能增加获得questions对象吗

### ISSUE THREAD

**Issue by zjlx** [7sDream/zhihu-oauth#5]
就跟zhihu-py3里面的: 获取收藏夹内所有问题对象.非常感谢.

**Comment by zjlx** [comment]
已经弄明白了,先获得answers对象,然后通过answers再获得questions就行了,还是感谢:)

**Comment by 7sDream** [comment]
恩，因为OAuth好像并没有直接获取收藏夹问题的接口～因为知乎是不公开的，所以我也是在慢慢的猜。。。
