### ISSUE TITLE
少年我来跟你说个噩耗。。。

### ISSUE THREAD

**Issue by YaoZeyuan** [7sDream/zhihu-oauth#53]
https://www.zhihu.com/api/v4/members/404-Page-Not-found/answers

昨天刚适配完zhihu-oauth库[捂脸]

**Comment by knarfeh** [comment]
这是。。。zhihu 的 api 公开了？

**Comment by 7sDream** [comment]
据我所知……这个 API 貌似只有一部分……不是很全……

静观其变ing
