### ISSUE TITLE
能否获取pid

### ISSUE THREAD

**Issue by huluobotouer** [7sDream/zhihu-oauth#56]
rt

**Comment by 7sDream** [comment]
请完善你的问题描述……蟹蟹……

**Comment by huluobotouer** [comment]
想要获取用户的url或者是用户的pid.
*****************************************
people(pid)
获取用户对象，需要 Client 是登录状态。
参数:	pid (str|unicode) – 用户 ID，注意，类型是字符串。
举例:	https://www.zhihu.com/people/abcdefg 的用户 ID 是 abcdefg。

**Comment by 7sDream** [comment]
参见 Issue #4

**Comment by 7sDream** [comment]
参见 Issue #4。

**Comment by huluobotouer** [comment]
好的，非常感谢。
PS：我想说，谢谢作者，这个包很好用！
