### ISSUE TITLE
device接口

### ISSUE THREAD

**Issue by wuming2** [7sDream/zhihu-oauth#57]
今天都在研究知乎的API，反编译了android APK，找到signature方法也拿到了token

但是有参数udid始终拿不到；跟踪是在首次启动app 使用 https://appcloud.zhihu.com/v1/device 接口来获取。里边有另一套签名算法……最新4.13版本使用jni加密，4.7版本使用java加密。但是参数死难找
现在我认为应该包含appid，  timestamp， app secretid，tampstamp 还有一个参数死活追踪不到了……
不知有没有大神一起追一下
4.13版本 在类CloudIDHelper中
4.7在com.zhihu.android.a.a里

**Comment by 7sDream** [comment]
目前来看这个参数使用固定值不会影响功能，我就暂时没管……

有时间的话我再看看。

**Comment by wuming2** [comment]
@7sDream 不是固定值哦，虽然暂时不传也没影响；但搞不出来总感觉不爽。没准哪天就拿这个来过滤请求了呢

**Comment by 7sDream** [comment]
用这个过滤那换一个不就得了……

是说「使用」固定值没影响，而不是说它就是固定值……
