### ISSUE TITLE
关于zhihu_oauth修改了python中built-in的class类的严重问题

### ISSUE THREAD

**Issue by zhaoyizhaoyi** [7sDream/zhihu-oauth#58]
作者你好，
非常感谢你写的这个包，文档很详尽，按着操作确实可以迅速爬取到自己需要的数据。但是现在出现了一个很严重的问题：
在你的streaming.py文件中，似乎对python的built-in的一些方法做了改写。
我在卸载了你的包之后，发现python被改写的类出问题了。例如我在用pandas读取数据时，便出现了如下的问题：
![image](https://cloud.githubusercontent.com/assets/13820796/22100985/5d8302b2-de6c-11e6-909b-e6a2e2fafa07.png)

我在卸载了python再重装之后都出现了这个问题，而且重置电脑之后问题也没有消失。
现在我的python版本是3.5.2，在anaconda里面装python也会出现这个问题。
不知道有什么想法不，谢谢~

**Comment by lbc001** [comment]
能否给一下代码复现呢～等会我也操作一下看看。但是我看了看streaming.py里面的东西貌似只定义了西夏StreamJSON。

**Comment by 7sDream** [comment]
@zhaoyizhaoyi 

嗯，麻烦详细描述一下你的环境，还有你的操作流程，能给执行的代码就更好了。

目前我看了代码，并没有修改 built-in 的东西，而且就算修改了，也应该不会固化在 Python 里的，最多也就影响一次。

我怀疑是你安装方式的问题？或者说是 Anaconda 对于 package 管理有 Bug……

没有详细描述的话我这也判断不了，而且目前并没有别人能复现你这个问题……

迷茫中。

**Comment by zhaoyizhaoyi** [comment]
@7sDream 谢谢你的解答，这个问题我已经解决了。
应该不是包里面的问题，可能是我自己的环境出了问题，现在数据已经正常了。
添麻烦了~
