### ISSUE TITLE
能不能保存一下图片的链接？

### ISSUE THREAD

**Issue by kerlingcode** [7sDream/zhihu-oauth#59]
我想顺便把图片保存下来。但是使用client.question 获取id之后他把 图片的 连接全部丢掉了

**Comment by 7sDream** [comment]
没太看懂。

你是想保存用户答案里的图片么？还是说问题描述里的？

最好给个例子吧，谢谢。

**Comment by kerlingcode** [comment]
之前说错了，是answer.save，这样保存的html是不带图片链接的，我是想把答案的文字与图片同时存下来，不知道是不是方法没使用正确，还是目前没办法实现呢？手册只看了一半就来提issue了，抱歉。

![4aac7e8ace4fefc71b15547977cfb92d](https://cloud.githubusercontent.com/assets/21171415/22195134/6243cef4-e181-11e6-9720-f66c4077d5d6.png)
![df651ca3e889e9790c671e1329d5c063](https://cloud.githubusercontent.com/assets/21171415/22195135/624fd406-e181-11e6-9754-af1e1c2b4a93.png)

**Comment by 7sDream** [comment]
https://www.zhihu.com/question/36114085/answer/142420931

`answer.save` 会保存图片的呀~

```python
answer = client.answer(142420931)
answer.save(answer.question.title)
```

比如你这样保存一个答案，得到的文件内容大概是这样的：

![](http://rikka-10066868.image.myqcloud.com/0d3b11c4-30ed-4015-8139-29fcc1b64744.png)

上面两个 `img` 标签就是图片呀。

[这里](https://transfer.sh/5CmAs/answer.html)是保存出的文件，你可以下载下来，用自己的浏览器直接打开试试。

**Comment by kerlingcode** [comment]
那您有写有把图片一起也保存下来的方法吗？没有的话那就我自己实现了。。。打扰了。。。 前面看答案看错了 发现没有图片 oRz
