### ISSUE TITLE
请问调用collection.answer_count出错是怎么回事呢

### ISSUE THREAD

**Issue by Allen286** [7sDream/zhihu-oauth#6]
问题1：
调用collection.answer_count出错是怎么回事呢？follower_count等其他属性都能正常返回，但answer_count会出错
```
collection = client.collection(26488229)
print(collection.follower_count)
print(collection.answer_count)
```
```
C:\Python27\python.exe C:/learnpython/zhihu_sp/temp.py
15649
Traceback (most recent call last):
  File "C:/learnpython/zhihu_sp/temp.py", line 20, in <module>
    print(collection.answer_count)
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\other.py", line 57, in wrapper
    return cls(cache['id'], cache, self._session)
TypeError: 'int' object has no attribute '__getitem__'
```

问题2：
调用people类的following_collections, 切换people id，但每次返回的都是我自己关注的收藏夹数，获取不到其他用户的数据。这是为什么呢？

问题3：
for in循环问题关注者列表或用户关注者列表时，中途终止，提示如下
```
  File "C:/learnpython/zhihu_sp/main.py", line 46, in getUserData
    for fol in people.followers:
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 155, in __next__
    obj = self[self._index]
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 129, in __getitem__
    self._fetch_more()
  File "C:\Python27\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 94, in _fetch_more
    'a json string, has data and paging'
zhihu_oauth.exception.UnexpectedResponseException
```
若能解答非常感谢！谢谢！

**Comment by 7sDream** [comment]
@Allen286 

Q1：确实是 bug，已确认，原因是内部一个装饰器使用错误，下一版本会修复。

Q2：貌似是这样的：虽然知乎提供了 following_collections，而且有个参数是用户ID，但是其实是没有权限获取「其他用户关注了哪些专栏」的，只能获取自己的。因为就算官方APP里也看不到别人关注了哪些的。但是「当前登录用户创建的收藏夹」是可以获取到的。（通过 `People.collections` 方法）。这是知乎限制的，我也没有办法。下一版本会将 `following_collections` 从 `People` 类移动到 `Me` 类里，同时文档也会更新。

Q3：看报错是获取数据的时候知乎返回了预期以外的数据（格式错误，或者直接没返回有效数据），请问这个问题是每次都发生么？如果是的话，请将 `for in` 循环用 `try except` 包起来：

```python
try:
    for people in user.followings:
        print(people.name)
except Exception as e:
    print(str(e))
```

我需要完整的错误信息来判断是哪里出错了……

---

PS：谢谢你帮我找 Bug……

**Comment by Allen286** [comment]
关于Q2：
> （按照这么说其他的 `following_xxx` 也有可能只有 `Me` 能用？我晚点测试下。）
其他`following_xxx`属性都可以用的，如关注话题和关注专栏等官方app个人用户界面都能看到，个人界面看不到的如`following_questions`属性也是可以用的，返回正确。
关于Q3：
爬较少量数据（如几千）时没有发生，但数据量较大比如获取张佳玮粉丝时，爬了几万条就中断了，已添加`try except`，还没测试，谢谢您！
Q4：
请问`People`类中能否增加个人主页被浏览次数这个属性呢？
谢谢！

**Comment by 7sDream** [comment]
恩，其他的 `following_xxx` 我也测试了，确实可以使用……

Q3：那估计就是正常的因为请求太频繁了……造成服务器限制了吧，这个解决起来有些麻烦，我以后版本尽量修吧。

Q4：APP 上没法看到基本就是没法获取了，因为这个库就是偷偷用了安卓 APP 使用的 API

我等下发布一个新版本，把 Q1 和 Q2 修复了先。

**Comment by 7sDream** [comment]
@Allen286 0.0.6 已发布。
