### ISSUE TITLE
People能否增加个人知乎主页url？

### ISSUE THREAD

**Issue by VegetaPn** [7sDream/zhihu-oauth#61]
你好：
请问People类里能否增加"个人主页url"或者“个性域名”的属性？
知乎个性域名url的格式一般为https://www.zhihu.com/people/${userSelfDefinedName}/activities

**Comment by 7sDream** [comment]
你把用户的 hash ID 填入你这个模板里，知乎会自动跳转到对应用户的主页的。

具体请看 Issue #4。

**Comment by VegetaPn** [comment]
知道了，谢谢！
