### ISSUE TITLE
搜索有 API 吗？

### ISSUE THREAD

**Issue by Axure** [7sDream/zhihu-oauth#62]

**Comment by 7sDream** [comment]
目前还没写，加到 todolist 里吧，如果有时间我写写。

**Comment by 7sDream** [comment]
这个写起来好像比较简单，我优先级提高点吧，预计在 18 到 19 好搞定。
发行版本的时候我艾特你一下。

**Comment by 7sDream** [comment]
@Axure 

更新一下 0.0.36 版本吧，搜索功能写完了，[Changelog](https://github.com/7sDream/zhihu-oauth/blob/master/changelog.md#0036)。

[搜索功能的文档](http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/search.html)。

可以帮忙测下有没有 Bug，因为写的急估计在所难免。

更新完普通使用没问题的话请关闭 Issue，如果发现 Bug 请另开一个，Thanks。
