### ISSUE TITLE
请问activity里面为什么没有“关注其他用户”呢？

### ISSUE THREAD

**Issue by divinites** [7sDream/zhihu-oauth#65]
根据文档，似乎关注所有其他的都有，但是就是没有关注用户这个activity的。
`zhihu_oauth.zhcls.activity.ActType = SimpleEnum({'FOLLOW_TOPIC', 'LIKE_PIN', 'CREATE_ARTICLE', 'FOLLOW_QUESTION', 'CREATE_ANSWER', 'JOIN_LIVE', 'FOLLOW_COLLECTION', 'COLLECT_ARTICLE', 'FOLLOW_ROUNDTABLE', 'CREATE_PIN', 'CREATE_QUESTION', 'COLLECT_ANSWER', 'VOTEUP_ARTICLE', 'VOTEUP_ANSWER', 'FOLLOW_COLUMN', 'PUBLISH_LIVE', 'VOTEUP_EBOOK'})`

那么我想获得A用户关注B用户的时间戳，可以用什么方式呢？谢谢！

**Comment by 7sDream** [comment]
项目的 API 用的是 Android 端的。
我试了一下手机客户端，点开自己的主页往下滑，是看不到「关注用户」这个动态的……

所以知乎的 API 里就没有定义这个动作，我也没办法呀……

关注的时间戳目前看来好像是没啥办法……

**Comment by divinites** [comment]
对，动态里面是没有“关注某个人”的，所以is_follower 这个状态变量切换的时间，目前是无从得知的？

**Comment by 7sDream** [comment]
是呀……除非你一直监控着某个人的关注列表……
