### ISSUE TITLE
建议把获取个性域名ID加进去

### ISSUE THREAD

**Issue by mnichangxin** [7sDream/zhihu-oauth#66]
知乎的个性域名 ID，也就是个人主页网址下的 https://www.zhihu.com/people/mnichangxin

ID 即为个性域名，现在需要这个 ID，希望能解决

**Comment by 7sDream** [comment]
你试试访问一下这个链接：https://www.zhihu.com/people/7d3d1b18949daf3d76bba4bb1cced479

---

提问之前请先搜索一下已有 Issue

这个问题已经很回答过很多很多遍了，见 Issue #4。

**Comment by mnichangxin** [comment]
我需要这个存储这种可读的ID应该怎么办，有相应的转换方法嘛

**Comment by 7sDream** [comment]
这种可读 ID 在我看来是完全没有必要的……
如果你需要可读性，昵称是一个更好的选择，同时储存 hashid，需要的时候自己访问一下就行。
如果需要唯一性，只要储存 hashid 即可。
这种只在 web 上用的 id 在我看来完全没有什么用啊……
---
如果你真的很需要（虽然我想不出来为什么），你可以自己写个函数，按照上一条那样的格式访问，返回的数据里会有 web id，自己用喜欢的方法提取出来就行……
我的库不打算提供这个函数，因为知乎给的数据里全是 hashid

**Comment by mnichangxin** [comment]
嗯嗯 谢谢！
