### ISSUE TITLE
Topic 对象的 id 有时是 str 类型的

### ISSUE THREAD

**Issue by tonyxty** [7sDream/zhihu-oauth#68]
通过 `people.following_topics` 获取的 `Topic` 对象, 其 `id` 是字符串类型的（其实似乎是服务器端有问题，服务器返回的 json 中的 `id` 是字符串），但通过 `client.topic()` 创建的对象 `id` 必须是 `int` 类型的，导致通过不同方式获取的 `Topic` 对象行为不同。

建议在构造数字 `id` 的对象时进行类型转换。

**Comment by 7sDream** [comment]
收到，我睡觉起来之后看看怎么处理，应该在下一版本发布时会处理好。

**Comment by 7sDream** [comment]
@tonyxty 

0.0.39 版本应该解决了这个 Bug，你可以再试试。

如果可以的话麻烦给个反馈，Thx。

**Comment by tonyxty** [comment]
并没有，实际上变得更加奇怪了：在刚刚构造对象时 `id` 是 `int` 类型的，但从服务器取得过数据之后就变成 `str` 类型了。可以用如下代码进行测试：

```python
import zhihu_oauth

client = zhihu_oauth.ZhihuClient()
client.load_token('token.pkl')

me = client.me()

print(zhihu_oauth.__version__)  # 0.0.39

topic = me.following_topics[0]  # 通过其他对象构造
print(type(topic.id))           # <class 'int'>
print(topic.name)               # 进行网络访问，从服务器取得数据
print(type(topic.id))           # 变成 <class 'str'> 了！

topic = client.topic(19776749)  # 手动构造
print(type(topic.id))           # <class 'int'>
print(topic.name)               # 「根话题」
print(type(topic.id))           # 也变成 <class 'str'> 了！
```

**Comment by 7sDream** [comment]
这次是把自动构造的对象的给统一了……
想了一下手动的话确实还会有这种现象……
今晚我抽空弄一下。

**Comment by 7sDream** [comment]
@tonyxty 

试试看 0.0.39.post1 吧

ID 这一快当初处理的时候确实没想到知乎会返回类型不同的数据，所以比较难弄……

我也不确定是不是完全修好了，如果有问题的话欢迎继续提。

**Comment by tonyxty** [comment]
@7sDream 

看来修好了，多谢！辛苦了～
