### ISSUE TITLE
能不能支持JSON源码备份功能

### ISSUE THREAD

**Issue by prid** [7sDream/zhihu-oauth#69]
使用场景：我想对我自己的收藏夹定时做个备份，每个备份中包含了所有的答案/文章，以及其中的评论。

做备份的时候我想收集尽可能全的信息（也就是服务器的原始返回数据），比如发布时间，作者，评论数，赞同数。

能不能出个save_json的函数，保留尽可能多的服务器的原始返回数据？

**Comment by 7sDream** [comment]
请使用所有知乎类对象都有的 pure_data 属性，参看文档：http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-dev/zhcls/base.html#zhihu_oauth.zhcls.base.Base.pure_data

**Comment by 7sDream** [comment]
三天未回复，关闭 Issue
