### ISSUE TITLE
不能使用代理

### ISSUE THREAD

**Issue by maplewizard** [7sDream/zhihu-oauth#7]
代理出现错误：

ConnectionError: HTTPSConnectionPool(host='api.zhihu.com', port=443): Max retries exceeded with url: /captcha (Caused by ProxyError('Cannot connect to proxy.', error('Tunnel connection failed: 302 Found',)))

用urllib2 测试代理正常。

**Comment by 7sDream** [comment]
我测试了一下（Python 3.5 和 2.7），并没能复现这个问题，请问你是 100% 出错么 。

对了，目前只支持 HTTP 代理的，如果你确实是用的 HTTP 代理的话，请给出系统版本，Python 版本，能复现你错误的最少代码，我再去研究，谢谢。

**Comment by maplewizard** [comment]
应该是连接的问题，已正常
