### ISSUE TITLE
如何将答案保存为markdown或者txt文件？

### ISSUE THREAD

**Issue by tangsengqimadongnagedong** [7sDream/zhihu-oauth#70]

**Comment by 7sDream** [comment]
这个项目不提供 md 功能，你可以[保存成 HTML](http://zhihu-oauth.readthedocs.io/zh_CN/latest/guide/use.html#backup-save) 之后随便用个其他项目做转换。

比如：[html2md](https://bitbucket.org/greyw/html2md)，[pandoc](http://pandoc.org/MANUAL.html) 都可以。

**Comment by tangsengqimadongnagedong** [comment]
多谢
