### ISSUE TITLE
没有获取question浏览量的方法吗？

### ISSUE THREAD

**Issue by MasterVan** [7sDream/zhihu-oauth#73]
右边的
![image](https://cloud.githubusercontent.com/assets/12422102/26244961/94dc833a-3cc4-11e7-9ade-047f9c203dbd.png)

**Comment by 7sDream** [comment]
手机客户端上好像没有这个数值，所以目前没有……

**Comment by MasterVan** [comment]
@7sDream 
好吧，我自己写了一部分获取到了，灰常谢谢你~

**Comment by Yuning06** [comment]
怎样获得浏览量的数据呢？
