### ISSUE TITLE
是否可以设置update属性?

### ISSUE THREAD

**Issue by Ericxiaoshuang** [7sDream/zhihu-oauth#74]
比如 获取登录用户的 粉丝数量
me.follower_count
貌似不能实时跟新
是否可以设置一个me.follower_count(update)
来监控变化?

**Comment by 7sDream** [comment]
```python
me.refresh()
me.follower_count
```

为了网络考虑属性全都做了缓存，如果需要更新手动调用 refresh 即可。

**Comment by Ericxiaoshuang** [comment]
@7sDream 非常感谢
