### ISSUE TITLE
将zhihu-oauth的github url写在一篇知乎文章中保存，会被知乎暂时封禁账号

### ISSUE THREAD

**Issue by minzhang** [7sDream/zhihu-oauth#75]
注册了一个知乎小号准备来测试zhihu-oauth。为了以后查阅方便就写了一篇文章，把https://github.com/7sDream/zhihu-oauth 记在文章中。点击保存后，账户立刻被封，后来通过手机短信解封了。看来知乎的反爬虫策略里面有这个url。

**Comment by 7sDream** [comment]
@minzhang 

这么可怕的吗？我晚上有时间的话测试一下。

**Comment by 7sDream** [comment]
@minzhang 

我刚刚创建了个小号发了一篇试了一下，并没有发生任何疑似帐号被封禁的现象呀……

能不能具体说明一下你的操作流程和文章内容？

可能是其他关键字触发了屏蔽？

**Comment by minzhang** [comment]
额，具体已经不记得了，也许是在标题中有爬虫之类的字眼。

文章内容只有https://github.com/7sDream/zhihu-oauth这一行而已。

只是汇报一下我遇到的状况，可能并非是zhihu-oauth导致的。
