### ISSUE TITLE
如何获取的登录用户的timeline？

### ISSUE THREAD

**Issue by zyh3838438zyh** [7sDream/zhihu-oauth#76]

**Comment by 7sDream** [comment]
@zyh3838438zyh 

timeline 由于类型复杂且一直在增加，所以暂时还没写。

如果 7 月上旬中旬不忙的话可能会尝试完成这个功能。

**Comment by zyh3838438zyh** [comment]
@7sDream 
好的，感谢您的回复，也感谢您提供了这样一个库。期待您的更新。

**Comment by 7sDream** [comment]
@zyh3838438zyh 

这两天把 Feed 写了一下，发了个新版本（0.0.40.post1），可以更新试用一下……

Feed 的类型比较多，我也不能保证所有的都测试过，如果发现了 Bug 请另外提个 Issue。

相关文档：http://zhihu-oauth.readthedocs.io/zh_CN/latest/for-user/zhcls/feed.html
