### ISSUE TITLE
读取Feed时产生UnimplementedException

### ISSUE THREAD

**Issue by doradayel** [7sDream/zhihu-oauth#78]
Traceback (most recent call last):
  File "D:\temp\zhtltest.py", line 8, in <module>
    FeedType.CREATE_ANSWER, FeedType.COLLECT_ANSWER,
  File "C:\Anaconda3\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 188, in __next__
    obj = self[self._index]
  File "C:\Anaconda3\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 163, in __getitem__
    return self._build_obj(self._data[item])
  File "C:\Anaconda3\lib\site-packages\zhihu_oauth\zhcls\generator.py", line 295, in _build_obj
    obj = self._obj_cls(data, self._session)
  File "C:\Anaconda3\lib\site-packages\zhihu_oauth\zhcls\feed.py", line 136, in __init__
    self._type = _verb_to_feed_type(self._data['verb'])
  File "C:\Anaconda3\lib\site-packages\zhihu_oauth\zhcls\feed.py", line 87, in _verb_to_feed_type
    'Unknown feed verb: {0}'.format(verb)
zhihu_oauth.exception.UnimplementedException: Meet a unimplemented condition: Unknown feed verb: COLUMN_POPULAR_ARTICLE. Please send this error message to developer to get help.

用的是示例代码，尝试了几次每次都会在不同的位置抛出异常的，不是特定的某一条feed.

**Comment by 7sDream** [comment]
嗯，Feed 功能刚写没多久，而且因为 Feed 类型众多，有一两种我这里没遇到的也算正常。
我明天看看这种类型，可能的话明天可能出一个新的版本。

这种情况可能还需要持续一两个版本，望谅解。

**Comment by 7sDream** [comment]
@doradayel 

如果可能的话，能不能麻烦用客户端截一张这种类型的 Feed 的图？
因为我这里没有这种类型的，所以有些东西比较难判断，强行写怕还是有 Bug。

从名字来看这种类型可能会被描述成「某专栏的热门文章」之类的，劳烦找找。

如果找不到的话我就先按猜测写，也没关系。

**Comment by doradayel** [comment]
每次抽取的Feed流中项目的顺序是不一样的，不太好判断是哪一条。我根据首页内容找了下，应该是某个topic下有column更新。建议可以关注下“机器学习”topic，应该能碰到这种feed。

另外建议遇到没见过的类型能够设置跳过而不是直接抛出异常，这样以后知乎如果加新类型，没更新时还可以用。直接在for上加异常处理，遇到一个异常之后就不能继续了。

**Comment by 7sDream** [comment]
@doradayel 

你开启新版首页了嘛，我关注了一些 topic 依旧没有这种 Feed……

跳过这个设定我考虑一下，下一版本可能的话把这个 Exception 转成 Warning 好了。

**Comment by 7sDream** [comment]
@doradayel 

刚刚更新了一个新的 dev 的 pre release 版本 `0.0.41.dev1`，你可以升级测试下。

```bash
sudo pip3 install -U --pre zhihu_oauth
```

如果可能的话在获取到 `COLUMN_POPULAR_ARTICLE` 类型的时候输出一下原始数据，然后贴上来。

```python
for feed in me.feeds.filter(FeedType.COLUMN_POPULAR_ARTICLE):
    print(feed._data)
```

这样就行，可能需要等待的时间比较久，输出了一个数据之后就可以停止了。

**Comment by doradayel** [comment]
这是其中一个输出：

{'action_text_tpl': '来自: {}', 'target': {'comment_permission': 'all', 'author': {'name': '何瑫', 'is_following': False, 'headline': 'GQ中国总主笔 微信公众号nonfiction2016', 'id': '93de303f63f33f1db533635687df7f0b', 'is_followed': False, 'gender': 1, 'avatar_url': 'https://pic1.zhimg.com/50/v2-c011f419afb44dd03f67127776819d34_s.jpg', 'url_token': 'he-tao-62-44', 'user_type': 'people', 'is_org': False, 'url': 'https://api.zhihu.com/people/93de303f63f33f1db533635687df7f0b', 'badge': [{'description': '特稿记者，《智族GQ》总主笔', 'type': 'identity'}], 'type': 'people'}, 'image_url': 'https://pic4.zhimg.com/50/v2-fba422ca65c3c94b6cf9d5b6a894f2eb_hd.jpg', 'updated': 1498477243, 'voteup_count': 66, 'linkbox': {'pic': '', 'category': '', 'url': '', 'title': ''}, 'column': {'comment_permission': 'all', 'author': {'name': '匿名用户', 'user_type': 'people', 'headline': '', 'url': '', 'id': '0', 'type': 'people', 'avatar_url': 'https://pic2.zhimg.com/aadd7b895_s.jpg', 'url_token': ''}, 'url': 'https://api.zhihu.com/columns/hetao', 'title': '何瑫的写作工坊', 'id': 'hetao', 'updated': 1488505869, 'type': 'column', 'intro': '为你精挑细选最优质的非虚构作品，以及采访手记、采…', 'image_url': 'https://pic2.zhimg.com/b7e9343847e8279d39070ec1c048ca61_r.jpg'}, 'preview_text': '', 'excerpt': '若是论起作者对文字细节的把控，今天推荐的这篇文章堪称翘楚。从文本属性而言，它是一篇讣闻，这一直是我非常爱读的一类文章，讣闻中诞生了许多经典的人物写作，它是浓缩的精华，用短短几千字就要书写人的一生，这不是件容易事。 如果有兴趣，你可以将本文逐字…', 'excerpt_title': '', 'id': 27569868, 'title': '直到魔鬼都不敢跟他赌', 'excerpt_new': '若是论起作者对文字细节的把控，今天推荐的这篇文章堪称翘楚。从文本属性而言，它是一篇讣闻，这一直是我非常爱读的一类文章，讣闻中诞生了许多经典的人物写作，它是浓缩的精华，用短短几千字就要书写人的一生，这不是件容易事。 如果有兴趣，你可以将本文逐字…', 'created': 1498477243, 'preview_type': 'default', 'type': 'article', 'voting': 0, 'comment_count': 6, 'url': 'https://api.zhihu.com/articles/27569868'}, 'action_source': {'action_text': '来自: 何瑫的写作工坊', 'author_created': 1498477243, 'type': 'two_line', 'author_info': {'name': '何 瑫', 'is_following': False, 'headline': 'GQ中国总主笔 微信公众号nonfiction2016', 'id': '93de303f63f33f1db533635687df7f0b', 'is_followed': False, 'gender': 1, 'avatar_url': 'https://pic1.zhimg.com/50/v2-c011f419afb44dd03f67127776819d34_s.jpg', 'url_token': 'he-tao-62-44', 'user_type': 'people', 'is_org': False, 'url': 'https://api.zhihu.com/people/93de303f63f33f1db533635687df7f0b', 'badge': [{'description': '特稿记者，《智族GQ》总主笔', 'type': 'identity'}], 'type': 'people'}}, 'created_time': 1499918347, 'action_text': '来自: 何瑫的写作工坊', 'brief': '{"source": "TS", "type": "article", "id": 27569868}', 'verb': 'COLUMN_POPULAR_ARTICLE', 'uninterest_reasons': [{'reason_text': '写作', 'reason_type': 'topic', 'object_type': 'topic', 'reason_id': 3, 'object_token': '19552516'}, {'reason_text': '赌博', 'reason_type': 'topic', 'object_type': 'topic', 'reason_id': 3, 'object_token': '19968954'}, {'reason_text': '故事', 'reason_type': 'topic', 'object_type': 'topic', 'reason_id': 3, 'object_token': '19554143'}, {'reason_text': '何瑫创作的内容', 'reason_type': 'creator', 'object_type': 'people', 'reason_id': 2, 'object_token': '93de303f63f33f1db533635687df7f0b'}], 'updated_time': 1499918347, 'id': '116_1500294004.08', 'offset': 116, 'actors': [{'comment_permission': 'all', 'author': {'name': '匿名用户', 'user_type': 'people', 'headline': '', 'url': '', 'id': '0', 'type': 'people', 'avatar_url': 'https://pic2.zhimg.com/aadd7b895_s.jpg', 'url_token': ''}, 'url': 'https://api.zhihu.com/columns/hetao', 'title': '何瑫的写作工坊', 'id': 'hetao', 'updated': 1488505869, 'type': 'column', 'intro': '为你精挑细选最优质的非虚构作品，以及采访手记、采…', 'image_url': 'https://pic2.zhimg.com/b7e9343847e8279d39070ec1c048ca61_r.jpg'}], 'attached_info': 'CmEIxfuW/a77vJoOEAcaBzMyMTUxMDggu+XDygUoQjAGQHRKFQoBQxIFMTEzMjEYuPL2g9UrIAEoAlIWY29sdW1uX3BvcHVsYXJfYXJ0aWNsZVoFMTEzMjFyCDI3NTY5ODY4', 'show_actor_time': False, 'type': 'feed'}

**Comment by 7sDream** [comment]
@doradayel 

也就是说 dev 版本确实修复了此问题咯？那我等会改一个版本号发正式版。

同时也谢谢你提供的输出，我去看看有没有什么要改的地方。

以后使用如果看见 unimplement 的 warning 也欢迎继续反馈。

**Comment by doradayel** [comment]
是的，遇到没见过的类型会给出警告并自动跳过而不是抛出异常了。我觉得这样已经能用了，后面发现新的类型再慢慢加就行。

辛苦了，假期还在写代码。

**Comment by 7sDream** [comment]
@doradayel 

不客气，那下次看见这种 Warning 也欢迎反馈。
