### ISSUE TITLE
新手求教：Question类能拿到浏览量么？

### ISSUE THREAD

**Issue by wavwind** [7sDream/zhihu-oauth#79]
rt

**Comment by 7sDream** [comment]
数据应该是有的，只是没写接口。

你可以暂时使用 question.pure_data 来获取到 JSON 数据然后在里面找找……

下一个版本给你加上。

**Comment by wavwind** [comment]
question.pure_data里也没找到， 之前就是把question的所有属性都打出来的， 没找到。
我是用了一个问题， 网页显示被浏览273757次， 但是在json里连"273"都搜不到。
麻烦大佬了， 下个版本帮忙加一下哈

**Comment by 7sDream** [comment]
嗷，你说的是浏览量啊……那确实没有。

知乎 Android 端的 API 没有提供这个数据，我也难为无米之炊……

非要想获取的话你也只好自己根据 question id 访问网页版获取了
