### ISSUE TITLE
代理一直出warning

### ISSUE THREAD

**Issue by maplewizard** [7sDream/zhihu-oauth#8]
连上代理后，每一步都一直出现warning：
ProgramFiles/anaconda/lib/python2.7/site-packages/requests/packages/urllib3/connectionpool.py:791: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
这需要设置什么吗？

**Comment by 7sDream** [comment]
唔，是一个小问题，因为代码里设置代理时同时关闭了 SSL，所以会有warning，下一个版本会修复一下。

现在的话可以用以下代码忽略所有 warning：

```python
import warnings
warnings.filterwarnings("ignore")
```
