### ISSUE TITLE
如何获取头像原图地址？如何判断是否是默认头像？

### ISSUE THREAD

**Issue by qazujmko** [7sDream/zhihu-oauth#83]
默认只能拿到小图，怎么得到大图呢？

希望增加判断是否是默认头像的api 知乎不同用户的匿名头像地址也是不同的，似乎只能下载下来对比

**Comment by 7sDream** [comment]
1. `people.avatar.replace('_s', '_r')` 即为原图。
2. 额……这个应该没有，你自己观察一下有没有什么规律吧。

**Comment by Faronsince2016** [comment]
https://pic4.zhimg.com/ca6fe8128ea4d0fd5317523a9ac3d143_xl.jpg
https://pic4.zhimg.com/ca6fe8128ea4d0fd5317523a9ac3d143_l.jpg
https://pic4.zhimg.com/ca6fe8128ea4d0fd5317523a9ac3d143_m.jpg
https://pic4.zhimg.com/ca6fe8128ea4d0fd5317523a9ac3d143_s.jpg
https://pic4.zhimg.com/ca6fe8128ea4d0fd5317523a9ac3d143_**{size}**.jpg

难道不是这个？

**Comment by 7sDream** [comment]
@Faronsince2016 

Nice 整理。

r 应该是原图，其他的 size 标识符我其实没仔细研究过～
