### ISSUE TITLE
Base类里的refresh()方法无效

### ISSUE THREAD

**Issue by zaw007** [7sDream/zhihu-oauth#85]
我用refresh()方法后，再次打印属性，并没有再次去获取最新数据，我debug跟踪发现 self._data并没有成功赋值为None
我系统版本：win10 64位，python版本：2.7.12 64位

**Comment by 7sDream** [comment]
@zaw007 

能不能劳烦给个 [MWE](https://en.wikipedia.org/wiki/Minimal_Working_Example)。

我这里貌似没法复现。

**Comment by zaw007** [comment]
不好意思，我重新测试了一下，现在都正常了，可能是因为pycharm的原因，重开了下IDE就正常了。
