### ISSUE TITLE
请教一个问题，关于请求数据

### ISSUE THREAD

**Issue by zaw007** [7sDream/zhihu-oauth#87]
ZhihuClient类里返回的比如me，live等对象，他是在怎么请求数据的，我断点跟踪，发现Base类的_init_里，执行完self._data = None后，数据便请求完成，没看到有去执行 _get_data()方法，就想问问，请求数据是在哪做的?

**Comment by 7sDream** [comment]
出现这个的原因是因为这些对象里的属性基本是加了 property 装饰器和 normal_attr 装饰器的方法。

 IDE 的调试器为了显示 propert y变量的值，会去自动执行 `normal_attr` 装饰器。

至于为什么设置 `_data=None` 后才会有数据是因为 `normal_attr` 装饰器里用到了 `_data` 这个变量，当对象里没有这个变量的时候执行会出错，所以那时 IDE 无法显示值。

具体可以看这个知乎回答：https://www.zhihu.com/question/59024388/answer/161095485
