### ISSUE TITLE
使用搜索功能返回的结果，获取SearchResult中的对象后，有些属性得不到值

### ISSUE THREAD

**Issue by INTERNEST** [7sDream/zhihu-oauth#90]
比如我在使用搜索功能搜索知乎的问题，也就是Question对象，我从SearchResult中obj属性拿出Question对象后，想要得到这个Question的answers属性，但是却为空，想问如何得到一个线索，能够让我拿到answers或者请求到answers，而我找了半天也没有发现ID这个属性

**Comment by 7sDream** [comment]
@INTERNEST 

能否给一段测试代码，或者说明一下你搜索的关键词和问题 ID。

**Comment by 7sDream** [comment]
因为没有后续说明，暂时关闭。
