### ISSUE TITLE
爬取太多数据导致被ban

### ISSUE THREAD

**Issue by githubao** [7sDream/zhihu-oauth#91]
大神，你好。我现在想爬取知乎的话题数据，但是爬了几千条之后系统提示，“系统检测到您的帐号或IP存在异常流量，请输入以下字符用于确认这些请求不是自动程序发出”，之后就全部是403错误了。
为了应对这样的问题，能否提供一些解决思路。
目前自己能想到的有，发现被ban了，然后就更换账号使用新的账号登录，或者更改使用代理。
其实是希望有没有一劳永逸的方法。
感谢~~~

**Comment by 7sDream** [comment]
这个库并不是用来爬数据的，只是一个 API Client，起始目的是为了写一个第三方客户端，没有为大规模爬取做任何优化（比如多线程网络请求，线程池，方案配置，序列化，反反爬虫等）……

所以我并不提供任何关于大规模爬数据的技术支持。

**Comment by githubao** [comment]
@7sDream 嗯嗯，感谢。[愉快]

**Comment by wanfke** [comment]
@githubao 被禁有解决方案了吗

**Comment by githubao** [comment]
@wanfke 新建一个工程，定时爬取ip并验证ip的可用性，然后给爬虫的工程提供定时更新的可用的ip列表可以部分的解决问题。关键点在于ip地址池的质量。同样账号也是可以动态配置的，只要有足够的账号...

**Comment by cabbagehao** [comment]
@githubao 我挂了ip代理池也不行呢，貌似被禁是通过ip+用户名的方式？
