### ISSUE TITLE
关于登陆方式的请教（web端与安卓端）

### ISSUE THREAD

**Issue by chenrb** [7sDream/zhihu-oauth#98]
最近发现web端的登陆不再是以前那样只要提交_xsrf/username/password，而是像该项目中安卓端登陆一样，需要提交"client_id"、"grant_type"、"timestamp"、"source"、"signature"、"username"、“password"等参数作验证，在看了该项目的登陆方式之后，发现有一个ImZhihuAndroidClient类，在web端登陆也是应该要有一个这样的类，就是不知道这些参数从哪里找

**Comment by 7sDream** [comment]
这个用 Chrome 的 devtool 抓一次登录请求就差不多知道了。

- client_id: c3cef7c66a1843f8b3a9e6a1e3160e20
- grant_type: password
- timestamp: 当前时间戳
- source: com.zhihu.web
- username: 用户名（手机号邮箱）
- password: 密码

signature 是根据上面这些数据加上一个 secret 动态生成的，至于 secret 在哪你需要去 js 里面找一找了。

Android 版的密钥我是通过反编译 APK 找到的。

**Comment by JohnChan0047** [comment]
感谢回复，我先寻找这个secret，headers我直接复制浏览器的看看行不行。
